<script setup lang="ts">
import {ref,onMounted} from 'vue';
import {currentUser,request,resetCsrf,roleNames} from './api';
const ready=ref(false),busy=ref(false),error=ref(''),login=ref(''),password=ref(''),newPassword=ref(''),changing=ref(false);
onMounted(async()=>{try{currentUser.value=await request('/auth/me');}catch{}finally{ready.value=true;}});
async function signIn(){busy.value=true;error.value='';try{await request('/auth/login','POST',{login_id:login.value,password:password.value});password.value='';resetCsrf();currentUser.value=await request('/auth/me');}catch(e){error.value=(e as Error).message;}finally{password.value='';newPassword.value='';busy.value=false;}}
async function signOut(){try{await request('/auth/logout','POST');}catch(e){error.value=(e as Error).message;}finally{currentUser.value=null;resetCsrf();password.value='';}}
async function changePassword(){busy.value=true;error.value='';try{await request('/auth/password','POST',{current_password:password.value,new_password:newPassword.value});password.value='';newPassword.value='';changing.value=false;currentUser.value=null;resetCsrf();}catch(e){error.value=(e as Error).message;}finally{password.value='';newPassword.value='';busy.value=false;}}
</script>
<template>
  <div v-if="!ready" class="login"><p>연결 상태를 확인하고 있습니다…</p></div>
  <main v-else-if="!currentUser" class="login"><el-card><h1>Forest Arena</h1><p class="muted">로컬 관리자 · 승인된 계정으로 로그인</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top" @submit.prevent="signIn"><el-form-item label="로그인 ID"><el-input v-model="login" aria-label="로그인 ID" autocomplete="username" required/></el-form-item><el-form-item label="비밀번호"><el-input v-model="password" aria-label="비밀번호" type="password" autocomplete="current-password" required show-password/></el-form-item><el-button native-type="submit" type="primary" :loading="busy">로그인</el-button></el-form><p class="muted">계정 복구는 로컬 관리자 명령을 사용하세요.</p></el-card></main>
  <div v-else class="shell"><aside><div class="brand">FOREST ARENA<span>관리자 작업 공간</span></div><nav v-if="!currentUser.must_change_password"><router-link to="/">대시보드</router-link><router-link v-if="currentUser.role==='SUPER_ADMIN'" to="/admins">관리자 계정</router-link><router-link to="/guests">게스트</router-link><router-link to="/profiles">게임 프로필</router-link><router-link to="/matches">경기 이력</router-link><router-link to="/audit">관리자 작업 이력</router-link></nav><div class="local">127.0.0.1 · 개발용</div></aside><div class="workspace"><header><span>{{currentUser.display_name}} <el-tag size="small">{{roleNames[currentUser.role]}}</el-tag></span><div><el-button @click="changing=true">비밀번호 변경</el-button><el-button @click="signOut">로그아웃</el-button></div></header><main><template v-if="currentUser.must_change_password || changing"><h1>비밀번호 변경</h1><el-alert title="15~128자의 새 비밀번호를 설정하세요. 변경 후 다시 로그인합니다." :closable="false" type="info"/><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form class="password-form" label-position="top" @submit.prevent="changePassword"><el-form-item label="현재 비밀번호"><el-input aria-label="현재 비밀번호" v-model="password" type="password" autocomplete="current-password" required/></el-form-item><el-form-item label="새 비밀번호"><el-input aria-label="새 비밀번호" v-model="newPassword" type="password" autocomplete="new-password" minlength="15" maxlength="128" required/></el-form-item><el-button native-type="submit" type="primary" :loading="busy">비밀번호 저장</el-button><el-button v-if="!currentUser.must_change_password" @click="changing=false">취소</el-button></el-form></template><router-view v-else :key="$route.fullPath"/></main></div></div>
</template>
