<script setup lang="ts">
import {ref,onMounted} from 'vue';import {request,pretty} from './api';import ProfileEditor from './ProfileEditor.vue';
const props=defineProps<{kind:string}>();const title:Record<string,string>={guests:'게스트',profiles:'게임 프로필',matches:'경기 이력',audit:'관리자 작업 이력'};
const q=ref(''),page=ref(1),size=ref(25),total=ref(0),items=ref<any[]>([]),error=ref(''),busy=ref(false),detail=ref<any>(null),selected=ref(''),opened=ref(false);
const columns:Record<string,[string,string][]>= {guests:[['player_id','게스트 ID'],['display_name','표시 이름'],['created_at','생성 시각']],profiles:[['player_id','게스트 ID'],['display_name','표시 이름'],['revision','변경 번호'],['updated_at','수정 시각']],matches:[['match_id','경기 ID'],['status','상태'],['created_at','생성 시각']],audit:[['id','기록 번호'],['actor_id','관리자 ID'],['action','작업'],['target_id','대상'],['created_at','시각']]};
async function load(){busy.value=true;error.value='';try{const r=await request('/'+props.kind+'?'+new URLSearchParams({q:q.value,page:String(page.value),size:String(size.value)}));items.value=r.items;total.value=r.total;}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function open(row:any){error.value='';selected.value=String(row.player_id||row.match_id||row.id);try{detail.value=props.kind==='audit'?row:await request('/'+props.kind+'/'+selected.value);opened.value=true;}catch(e){error.value=(e as Error).message;}}
onMounted(load);
</script>
<template><h1>{{title[kind]}}</h1><p class="muted">검색 후 항목의 상세 정보를 확인하세요.</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><form class="toolbar" @submit.prevent="page=1;load()"><el-input v-model="q" aria-label="검색어" placeholder="ID, 이름 또는 작업 검색" clearable/><el-button native-type="submit" type="primary">검색</el-button><el-button @click="load">새로고침</el-button></form><el-table :data="items" v-loading="busy" empty-text="표시할 항목이 없습니다"><el-table-column v-for="[prop,label] in columns[kind]" :key="prop" :prop="prop" :label="label" show-overflow-tooltip/><el-table-column label="상세" width="85"><template #default="{row}"><el-button link type="primary" @click="open(row)">상세</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="size" :page-sizes="[25,50,100]" :total="total" layout="total, sizes, prev, pager, next" @change="load"/><el-dialog v-model="opened" :title="title[kind]+' 상세'" width="760px" destroy-on-close><template v-if="kind==='guests' || kind==='profiles'"><p class="detail-line">게스트 ID: {{selected}}</p><pre v-if="kind==='guests'">{{pretty(detail?.player)}}</pre><ProfileEditor v-if="detail?.profile" :id="selected" @saved="load"/><el-empty v-else description="저장된 프로필이 없습니다"/></template><template v-else-if="kind==='matches'"><h3>경기 결과</h3><pre>{{pretty(detail?.match)}}</pre><h3>참가자</h3><el-table :data="detail?.participants"><el-table-column prop="player_id" label="게스트 ID"/><el-table-column prop="character_id" label="캐릭터"/><el-table-column prop="slot" label="참가 슬롯"/></el-table><pre>{{pretty(detail?.participants)}}</pre></template><template v-else><p>작업: {{detail?.action}} · 관리자: {{detail?.actor_id}}</p><p>변경 이유: {{detail?.reason||'없음'}}</p><h3>변경 전</h3><pre>{{pretty(detail?.before_data)}}</pre><h3>변경 후</h3><pre>{{pretty(detail?.after_data)}}</pre></template></el-dialog></template>
