package com.forestarena.admin;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.boot.SpringApplication;import org.springframework.context.ConfigurableApplicationContext;import org.springframework.jdbc.core.JdbcTemplate;import java.nio.file.*;import java.net.*;import java.net.http.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
@EnabledIfEnvironmentVariable(named="ADMIN_TEST_DATABASE_URL",matches=".+")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AuthIntegrationTest {
 ConfigurableApplicationContext ctx;JdbcTemplate db;AccountService service;String base;Path key;List<UUID> ids=new ArrayList<>();final com.fasterxml.jackson.databind.ObjectMapper json=new com.fasterxml.jackson.databind.ObjectMapper();
 final String pw="integration-password-12345";String login="auth_test_"+UUID.randomUUID().toString().substring(0,8);UUID superId;
 @BeforeAll void start()throws Exception{key=Files.createTempDirectory("admin-auth-test").resolve("key.json");new CryptoService(key.toString()).addKey(true);var app=new SpringApplication(AdminApplication.class);ctx=app.run("--server.port=0","--spring.datasource.url="+System.getenv("ADMIN_TEST_DATABASE_URL"),"--spring.datasource.username="+System.getenv("ADMIN_TEST_DATABASE_USER"),"--spring.datasource.password="+System.getenv("ADMIN_TEST_DATABASE_PASSWORD"),"--admin.key-file="+key);base="http://127.0.0.1:"+ctx.getEnvironment().getProperty("local.server.port")+"/admin/api/v1";db=ctx.getBean(JdbcTemplate.class);service=ctx.getBean(AccountService.class);superId=create("SUPER_ADMIN",login);db.update("UPDATE admin.accounts SET must_change_password=false WHERE id=?",superId);}
 UUID create(String role,String name){var a=service.create(UUID.randomUUID(),Map.of("login_id",name,"password",pw,"display_name","검사 계정","email","test@example.test","role",role,"reason","자동 검사"),false);UUID id=(UUID)a.get("id");ids.add(id);return id;}
 @BeforeEach void isolateIpAttempts(){db.update("DELETE FROM admin.login_limits WHERE scope='ip' AND key_hash=?",SecurityConfig.digest("127.0.0.1"));}
 @AfterAll void stop()throws Exception{if(db!=null)db.update("DELETE FROM admin.login_limits WHERE scope='ip' AND key_hash=?",SecurityConfig.digest("127.0.0.1"));if(db!=null)for(UUID id:ids){db.update("DELETE FROM admin.audit_log WHERE target_id=? OR actor_id=?",id.toString(),id);db.update("DELETE FROM admin.sessions WHERE account_id=?",id);db.update("DELETE FROM admin.accounts WHERE id=?",id);}if(ctx!=null)ctx.close();if(key!=null){Files.deleteIfExists(key);Files.deleteIfExists(key.getParent());}}
 class Browser {HttpClient client=HttpClient.newBuilder().cookieHandler(new CookieManager(null,CookiePolicy.ACCEPT_ALL)).build();String token;
  HttpResponse<String> req(String method,String path,Object body,boolean csrf)throws Exception{var b=HttpRequest.newBuilder(URI.create(base+path)).header("Content-Type","application/json");if(csrf)b.header("X-CSRF-TOKEN",token);b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));return client.send(b.build(),HttpResponse.BodyHandlers.ofString());}
  void csrf()throws Exception{var r=req("GET","/auth/csrf",null,false);assertEquals(200,r.statusCode());token=json.readTree(r.body()).get("token").asText();}
  void login(String name)throws Exception{csrf();assertEquals(200,req("POST","/auth/login",Map.of("login_id",name,"password",pw),true).statusCode());csrf();}
 }
 @Test void authCsrfRolesSessionsAndEncryption()throws Exception{Browser b=new Browser();assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());b.csrf();assertEquals(403,b.req("POST","/auth/login",Map.of("login_id",login,"password",pw),false).statusCode());b.login(login);assertEquals(200,b.req("GET","/auth/me",null,false).statusCode());assertEquals(403,b.req("POST","/admins",Map.of(),false).statusCode());
  String viewerName=login+"_viewer";UUID viewer=create("VIEWER",viewerName);Browser v=new Browser();v.login(viewerName);assertEquals(403,v.req("GET","/admins",null,false).statusCode());assertEquals(403,v.req("PUT","/profiles/"+UUID.randomUUID(),Map.of(),true).statusCode());
  assertFalse(db.queryForObject("SELECT display_name_encrypted FROM admin.accounts WHERE id=?",String.class,superId) .contains("검사 계정"));assertEquals("검사 계정",service.safe(service.row(superId)).get("display_name"));
  service.endSessions(superId,superId,"검사 강제 종료");assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());b.login(login);db.update("UPDATE admin.sessions SET created_at=now()-interval '9 hours' WHERE account_id=?",superId);assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());b.login(login);db.update("UPDATE admin.sessions SET last_seen_at=now()-interval '31 minutes' WHERE account_id=?",superId);assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());
 }
 @Test void lockoutAndPasswordReset()throws Exception{String n=login+"_lock";UUID id=create("OPERATOR",n);Browser b=new Browser();b.csrf();for(int i=0;i<5;i++)assertEquals(401,b.req("POST","/auth/login",Map.of("login_id",n,"password","incorrect-password-123"),true).statusCode());assertEquals(401,b.req("POST","/auth/login",Map.of("login_id",n,"password",pw),true).statusCode());db.update("UPDATE admin.login_limits SET locked_until=now()-interval '1 second' WHERE scope='account' AND key_hash=?",SecurityConfig.digest(n));b.login(n);assertEquals(403,b.req("GET","/dashboard",null,false).statusCode());assertEquals(200,b.req("POST","/auth/password",Map.of("current_password",pw,"new_password",pw+"new"),true).statusCode());assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());assertFalse((Boolean)service.row(id).get("must_change_password"));}
 @Test void lastSuperAdminAndAuditRollback(){long count=db.queryForObject("SELECT count(*) FROM admin.accounts WHERE active AND role='SUPER_ADMIN'",Long.class);if(count==1){assertThrows(AdminFault.class,()->service.edit(superId,superId,Map.of("display_name","검사","role","VIEWER","active",true,"reason","금지 검사")));assertThrows(AdminFault.class,()->service.edit(superId,superId,Map.of("display_name","검사","role","SUPER_ADMIN","active",false,"reason","금지 검사")));}String n=login+"_rollback";assertThrows(RuntimeException.class,()->service.tx.executeWithoutResult(s->{create("VIEWER",n);throw new IllegalStateException("transaction cancel");}));assertEquals(0,db.queryForObject("SELECT count(*) FROM admin.accounts WHERE login_id=?",Integer.class,n));}
 @Test void independentOriginCookiesSessionRotationAndIpLimit()throws Exception{
  Browser b=new Browser();var first=b.req("GET","/auth/csrf",null,false);b.token=json.readTree(first.body()).get("token").asText();String initial=first.headers().firstValue("set-cookie").orElseThrow();
  var signed=b.req("POST","/auth/login",Map.of("login_id",login,"password",pw),true);assertEquals(200,signed.statusCode());String changed=signed.headers().firstValue("set-cookie").orElseThrow();assertNotEquals(initial.split(";")[0],changed.split(";")[0]);assertTrue(changed.toLowerCase().contains("httponly"));assertTrue(changed.toLowerCase().contains("samesite=strict"));assertFalse(changed.toLowerCase().contains("secure"));
  assertTrue(signed.headers().firstValue("content-security-policy").orElse("").contains("frame-ancestors 'none'"));assertEquals("nosniff",signed.headers().firstValue("x-content-type-options").orElse(""));
  for(String header:List.of("Origin","Sec-Fetch-Site")){var req=HttpRequest.newBuilder(URI.create(base+"/auth/me")).header(header,header.equals("Origin")?"http://evil.example":"cross-site").GET().build();assertEquals(403,b.client.send(req,HttpResponse.BodyHandlers.ofString()).statusCode());}
  String ip=SecurityConfig.digest("127.0.0.1");db.update("INSERT INTO admin.login_limits(scope,key_hash,failures,locked_until) VALUES('ip',?,30,now()+interval '15 minutes') ON CONFLICT(scope,key_hash) DO UPDATE SET locked_until=excluded.locked_until,failures=30",ip);
  try{Browser limited=new Browser();limited.csrf();assertEquals(401,limited.req("POST","/auth/login",Map.of("login_id",login,"password",pw),true).statusCode());}finally{db.update("UPDATE admin.login_limits SET failures=0,locked_until=NULL WHERE scope='ip' AND key_hash=?",ip);}
 }
 @Test void independentPermissionActiveAndResetRevokeSessions()throws Exception{
  for(String change:List.of("role","active","password")){String name=login+"_revoke_"+change;UUID id=create("OPERATOR",name);db.update("UPDATE admin.accounts SET must_change_password=false WHERE id=?",id);Browser b=new Browser();b.login(name);assertEquals(200,b.req("GET","/auth/me",null,false).statusCode());
   if(change.equals("password"))service.reset(superId,id,pw+"temporary","QA 초기화");else service.edit(superId,id,Map.of("display_name","QA","role",change.equals("role")?"VIEWER":"OPERATOR","active",!change.equals("active"),"reason","QA 세션 종료"));assertEquals(401,b.req("GET","/auth/me",null,false).statusCode());
  }
 }
 @Test void independentLastSuperWithoutConditionalSkip(){
  service.tx.executeWithoutResult(s->{s.setRollbackOnly();db.update("UPDATE admin.accounts SET active=false WHERE role='SUPER_ADMIN' AND id<>?",superId);assertEquals(1,db.queryForObject("SELECT count(*) FROM admin.accounts WHERE active AND role='SUPER_ADMIN'",Integer.class));assertEquals(409,assertThrows(AdminFault.class,()->service.edit(superId,superId,Map.of("display_name","QA","role","VIEWER","active",true,"reason","QA 마지막 계정"))).status);});
  service.tx.executeWithoutResult(s->{s.setRollbackOnly();db.update("UPDATE admin.accounts SET active=false WHERE role='SUPER_ADMIN' AND id<>?",superId);assertEquals(409,assertThrows(AdminFault.class,()->service.edit(superId,superId,Map.of("display_name","QA","role","SUPER_ADMIN","active",false,"reason","QA 마지막 비활성"))).status);});
 }
 @Test void independentPostgresKeyRotationKeepsHistoryReadable(){
  service.tx.executeWithoutResult(s->{s.setRollbackOnly();String original=(String)service.row(superId).get("display_name_encrypted");String history=db.queryForObject("SELECT reason_encrypted FROM admin.audit_log WHERE target_id=? ORDER BY id LIMIT 1",String.class,superId.toString());
   // Other fixtures use their own key files; isolate every account ciphertext inside this rolled-back transaction.
   db.update("UPDATE admin.accounts SET display_name_encrypted=?,email_encrypted=?",service.crypto.encrypt("검사 계정"),service.crypto.encrypt("test@example.test"));service.crypto.rotate(db,service.tx);String rotated=(String)service.row(superId).get("display_name_encrypted");assertNotEquals(original.split(":")[0],rotated.split(":")[0]);assertEquals("검사 계정",service.crypto.decrypt(rotated));assertEquals("자동 검사",service.crypto.decrypt(history));
  });
 }

}
