package com.forestarena.admin;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.junit.jupiter.api.io.TempDir;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.*;import org.springframework.transaction.support.TransactionTemplate;import java.nio.file.Path;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
@EnabledIfEnvironmentVariable(named="ADMIN_TEST_DATABASE_URL",matches=".+")
class RecoverIntegrationTest {
 @TempDir Path temp;
 @Test void recoveryAuditsAllChangesAndRollsBackOnAuditFailure(){
  String url=System.getenv("ADMIN_TEST_DATABASE_URL");assertTrue(url.endsWith("/forest_arena_admin_test_dev"),"복구 검사는 전용 DB에서만 허용합니다");var source=new DriverManagerDataSource(url,System.getenv("ADMIN_TEST_DATABASE_USER"),System.getenv("ADMIN_TEST_DATABASE_PASSWORD"));var db=new JdbcTemplate(source);var tx=new TransactionTemplate(new DataSourceTransactionManager(source));var crypto=new CryptoService(temp.resolve("keys.json").toString());crypto.addKey(true);var service=new AccountService(db,tx,crypto);String login="recover_"+UUID.randomUUID().toString().substring(0,8),old="old-integration-password",pw="new-integration-password";UUID id=(UUID)service.create(UUID.randomUUID(),Map.of("login_id",login,"password",old,"display_name","복구 검사","role","VIEWER","reason","복구 검사 fixture"),false).get("id");String trigger="recover_fail_"+id.toString().replace("-","");String hash=SecurityConfig.digest(login);
  try{db.update("UPDATE admin.accounts SET active=false,must_change_password=false WHERE id=?",id);db.update("INSERT INTO admin.sessions(id,account_id,session_version,created_at,last_seen_at) VALUES(?,?,0,now(),now())",SecurityConfig.digest("recover-session"+id),id);db.update("INSERT INTO admin.login_limits(scope,key_hash,failures,locked_until,window_started_at) VALUES('account',?,5,now()+interval '15 minutes',now())",hash);
   db.execute("CREATE FUNCTION admin."+trigger+"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='ADMIN_RECOVER' AND NEW.target_id='"+id+"' THEN RAISE EXCEPTION 'fixture audit rejected'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER "+trigger+" BEFORE INSERT ON admin.audit_log FOR EACH ROW EXECUTE FUNCTION admin."+trigger+"()");
   assertThrows(RuntimeException.class,()->service.recover(login,pw));var unchanged=service.row(id);assertEquals("VIEWER",unchanged.get("role"));assertEquals(false,unchanged.get("active"));assertTrue(service.encoder.matches(old,(String)unchanged.get("password_hash")));assertEquals(1,db.queryForObject("SELECT count(*) FROM admin.sessions WHERE account_id=?",Integer.class,id));assertEquals(1,db.queryForObject("SELECT count(*) FROM admin.login_limits WHERE scope='account' AND key_hash=?",Integer.class,hash));
   db.execute("DROP TRIGGER "+trigger+" ON admin.audit_log");service.recover(login,pw);var recovered=service.row(id);assertEquals("SUPER_ADMIN",recovered.get("role"));assertEquals(true,recovered.get("active"));assertEquals(true,recovered.get("must_change_password"));assertTrue(service.encoder.matches(pw,(String)recovered.get("password_hash")));assertEquals(0,db.queryForObject("SELECT count(*) FROM admin.sessions WHERE account_id=?",Integer.class,id));assertEquals(0,db.queryForObject("SELECT count(*) FROM admin.login_limits WHERE scope='account' AND key_hash=?",Integer.class,hash));var audit=db.queryForMap("SELECT * FROM admin.audit_log WHERE target_id=? AND action='ADMIN_RECOVER'",id.toString());assertTrue(audit.get("before_data").toString().contains("VIEWER"));assertTrue(audit.get("after_data").toString().contains("SUPER_ADMIN"));assertEquals("로컬 계정 복구",crypto.decrypt((String)audit.get("reason_encrypted")));
  }finally{db.execute("DROP TRIGGER IF EXISTS "+trigger+" ON admin.audit_log");db.execute("DROP FUNCTION IF EXISTS admin."+trigger+"()");db.update("DELETE FROM admin.audit_log WHERE target_id=?",id.toString());db.update("DELETE FROM admin.sessions WHERE account_id=?",id);db.update("DELETE FROM admin.accounts WHERE id=?",id);db.update("DELETE FROM admin.login_limits WHERE scope='account' AND key_hash=?",hash);}
 }
}
