import {test,expect,type Page} from '@playwright/test';
async function login(page:Page,id:string,password:string){await page.goto('/');await page.getByRole('textbox',{name:'로그인 ID',exact:true}).fill(id);await page.getByRole('textbox',{name:'비밀번호',exact:true}).fill(password);const response=page.waitForResponse(r=>r.url().endsWith('/auth/login')&&r.request().method()==='POST');await page.getByRole('button',{name:'로그인',exact:true}).click();const result=await response;if(!result.ok())await page.getByRole('textbox',{name:'비밀번호',exact:true}).fill('');expect(result.status(),'로그인 응답').toBe(200);}
const profile={schema_version:3,first_granted:true,nickname:'플레이어',characters:['ja-hyun'],accessories:[],selected_character:'ja-hyun',selected_accessory:'',opponent_character:'nabi',accessibility:{text_scale:1,reduce_visual_effects:false,haptics_enabled:true},minimap:{transparency:30,marker_style:'face',show_names:true}};
test('한국어 관리 흐름 · 화면 권한 · 변경 번호 · 같은 요청 재시도',async({page})=>{
 let user:any=null;let revision=1;let stored=structuredClone(profile);let saved:any;let failed=false;const audit:any[]=[];const accounts:any[]=[];
 await page.route('**/admin/api/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/api/v1','');const body=req.postDataJSON();let data:any={};
 if(path==='/auth/csrf')data={token:'test-token',headerName:'X-CSRF-TOKEN'};
 else if(path==='/auth/me'){if(!user)return route.fulfill({status:401,json:{error:'로그인이 필요합니다.'}});data=user;}
 else if(path==='/auth/login'){user={id:'admin',login_id:body.login_id,display_name:body.login_id,role:body.login_id==='viewer'?'VIEWER':body.login_id==='operator'?'OPERATOR':'SUPER_ADMIN',active:true,must_change_password:false};data=user;}
 else if(path==='/auth/logout'){user=null;}
 else if(path==='/dashboard')data={guests:1,profiles:1,matches:0,db_status:'연결됨',game_api_status:'연결됨',recent_matches:[],recent_actions:audit};
 else if(path==='/admins'&&req.method()==='POST'){accounts.push({...body,id:'new-admin',active:true});data=accounts.at(-1);}
 else if(path==='/admins')data={items:accounts,total:accounts.length};
 else if(path==='/profiles')data={items:[{player_id:'test-player',display_name:'테스트',revision}],total:1};
 else if(path==='/profiles/test-player'&&req.method()==='PUT'){
 if(!saved){saved=body;failed=true;return route.abort('failed');}
 expect(body).toEqual(saved);expect(req.headers()['x-csrf-token']).toBe('test-token');stored=body.profile;revision++;audit.push({id:1,action:'profile.update',target_id:'test-player',reason:body.reason,before_data:profile,after_data:stored});data={profile:stored,revision};}
 else if(path==='/profiles/test-player')data={profile:stored,revision};
 else if(path==='/catalog')data={characters:['ja-hyun','nabi'],accessories:['fixture-iron-armor']};
 else if(path==='/audit')data={items:audit,total:audit.length};else return route.fulfill({status:404,json:{error:'지원하지 않는 요청'}});
 await route.fulfill({json:data});});
 await login(page,'super','test-password-long');await page.getByRole('link',{name:'관리자 계정',exact:true}).click();await page.getByRole('button',{name:'관리자 생성',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'로그인 ID',exact:true}).fill('new-viewer');await dialog.getByRole('textbox',{name:'표시 이름',exact:true}).fill('신규 조회자');await dialog.getByRole('textbox',{name:'임시 비밀번호',exact:true}).fill('temporary-password-long');await dialog.getByRole('textbox',{name:'변경 이유',exact:true}).fill('테스트 계정 생성');await dialog.getByRole('button',{name:'계정 저장',exact:true}).click();await expect(page.getByText('new-viewer',{exact:true})).toBeVisible();await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await login(page,'operator','test-password-long');await page.getByRole('link',{name:'게임 프로필',exact:true}).click();await page.getByRole('button',{name:'상세',exact:true}).click();await page.getByRole('textbox',{name:'닉네임',exact:true}).fill('수정 이름');await page.getByRole('textbox',{name:'변경 이유',exact:true}).fill('프로필 표시 확인');await page.screenshot({path:'test-results/profile-editor.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'프로필 저장',exact:true}).click();await expect(page.getByRole('button',{name:'같은 요청 재시도',exact:true})).toBeVisible();await page.getByRole('button',{name:'같은 요청 재시도',exact:true}).click();await expect(page.getByText('변경 번호 2',{exact:false})).toBeVisible();expect(failed).toBe(true);await page.keyboard.press('Escape');await page.getByRole('link',{name:'관리자 작업 이력',exact:true}).click();await expect(page.getByText('profile.update',{exact:true})).toBeVisible();await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await login(page,'viewer','test-password-long');await expect(page.getByRole('link',{name:'관리자 계정',exact:true})).toHaveCount(0);await page.getByRole('link',{name:'게임 프로필',exact:true}).click();await page.getByRole('button',{name:'상세',exact:true}).click();await expect(page.getByText('조회자 권한: 프로필을 수정할 수 없습니다.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'프로필 저장',exact:true})).toHaveCount(0);
});

test('실제 서버 · 최고관리자 생성 → 운영자 수정 → 이력 → 조회자 서버 거부',async({page})=>{
 const env=process.env;test.skip(!env.ADMIN_E2E_SUPER_ID||!env.ADMIN_E2E_SUPER_PASSWORD||!env.ADMIN_E2E_OPERATOR_ID||!env.ADMIN_E2E_OPERATOR_PASSWORD||!env.ADMIN_E2E_VIEWER_ID||!env.ADMIN_E2E_VIEWER_PASSWORD||!env.ADMIN_E2E_PLAYER_ID,'실제 PostgreSQL과 변경 의무가 해제된 테스트 계정을 환경변수로 지정해야 합니다.');
 await login(page,env.ADMIN_E2E_SUPER_ID!,env.ADMIN_E2E_SUPER_PASSWORD!);await page.getByRole('link',{name:'관리자 계정',exact:true}).click();await page.getByRole('button',{name:'관리자 생성',exact:true}).click();const dialog=page.getByRole('dialog'),id='e2e-'+Date.now();await dialog.getByRole('textbox',{name:'로그인 ID',exact:true}).fill(id);await dialog.getByRole('textbox',{name:'표시 이름',exact:true}).fill('브라우저 검사 조회자');await dialog.getByRole('textbox',{name:'임시 비밀번호',exact:true}).fill(crypto.randomUUID());await dialog.getByRole('textbox',{name:'변경 이유',exact:true}).fill('브라우저 자동 검사');await dialog.getByRole('button',{name:'계정 저장',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await login(page,env.ADMIN_E2E_OPERATOR_ID!,env.ADMIN_E2E_OPERATOR_PASSWORD!);await page.getByRole('link',{name:'게임 프로필',exact:true}).click();await page.getByRole('textbox',{name:'검색어',exact:true}).fill(env.ADMIN_E2E_PLAYER_ID!);await page.getByRole('button',{name:'검색',exact:true}).click();await page.getByRole('button',{name:'상세',exact:true}).first().click();await page.getByRole('textbox',{name:'변경 이유',exact:true}).fill('브라우저 실제 연결 검사 (기존 프로필 유지)');await page.getByRole('button',{name:'프로필 저장',exact:true}).click();await expect(page.getByRole('textbox',{name:'변경 이유',exact:true})).toHaveValue('');await page.keyboard.press('Escape');await page.getByRole('link',{name:'관리자 작업 이력',exact:true}).click();await expect(page.getByRole('cell',{name:'profile.update',exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await login(page,env.ADMIN_E2E_VIEWER_ID!,env.ADMIN_E2E_VIEWER_PASSWORD!);await page.getByRole('link',{name:'게임 프로필',exact:true}).click();await page.getByRole('textbox',{name:'검색어',exact:true}).fill(env.ADMIN_E2E_PLAYER_ID!);await page.getByRole('button',{name:'검색',exact:true}).click();await page.getByRole('button',{name:'상세',exact:true}).first().click();await expect(page.getByText('조회자 권한: 프로필을 수정할 수 없습니다.',{exact:true})).toBeVisible();
 const status=await page.evaluate(async(playerId)=>{const c=await fetch('/admin/api/v1/auth/csrf').then(r=>r.json());return (await fetch('/admin/api/v1/profiles/'+playerId,{method:'PUT',headers:{'Content-Type':'application/json',[c.headerName]:c.token},body:JSON.stringify({})})).status;},env.ADMIN_E2E_PLAYER_ID!);expect(status).toBe(403);
});

test('변경 번호 충돌 시 최신 데이터 확인 후 다시 편집',async({page})=>{
 let revision=3;await page.route('**/admin/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/admin/api/v1','');let data:any={};if(path==='/auth/me')data={id:'operator',display_name:'운영자',role:'OPERATOR',must_change_password:false};else if(path==='/auth/csrf')data={token:'csrf',headerName:'X-CSRF-TOKEN'};else if(path==='/profiles')data={items:[{player_id:'player',revision}],total:1};else if(path==='/catalog')data={characters:['ja-hyun','nabi'],accessories:[]};else if(path==='/profiles/player'&&route.request().method()==='PUT'){revision=4;return route.fulfill({status:409,json:{error:'revision_conflict'}});}else if(path==='/profiles/player')data={profile:{...profile,nickname:revision===4?'최신 이름':profile.nickname},revision};else data={guests:1,profiles:1,matches:0,recent_matches:[],recent_actions:[]};await route.fulfill({json:data});});
 await page.goto('/#/profiles');await page.getByRole('button',{name:'상세',exact:true}).click();await page.getByRole('textbox',{name:'변경 이유',exact:true}).fill('동시 수정 검사');await page.getByRole('button',{name:'프로필 저장',exact:true}).click();await expect(page.getByText('변경 번호가 다르거나 요청이 충돌했습니다. 최신 데이터를 확인한 뒤 다시 편집하세요.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'프로필 저장',exact:true})).toBeDisabled();await page.getByRole('button',{name:'최신 데이터로 다시 열기',exact:true}).click();await expect(page.getByRole('textbox',{name:'닉네임',exact:true})).toHaveValue('최신 이름');await expect(page.getByText('변경 번호 4',{exact:false})).toBeVisible();
});

test('비밀번호 변경 의무 계정은 변경 폼만 표시',async({page})=>{
 await page.route('**/admin/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/admin/api/v1','');if(path==='/auth/me')return route.fulfill({json:{id:'forced',display_name:'신규 관리자',role:'VIEWER',must_change_password:true}});if(path==='/auth/csrf')return route.fulfill({json:{token:'csrf',headerName:'X-CSRF-TOKEN'}});if(path==='/auth/password'){expect(route.request().postDataJSON()).toEqual({current_password:'old-password-long',new_password:'new-password-long'});return route.fulfill({json:{ok:true}});}throw new Error('변경 의무 계정의 예기치 않은 요청: '+path);});
 await page.goto('/');await expect(page.getByRole('heading',{name:'비밀번호 변경',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'게임 프로필',exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:'현재 비밀번호',exact:true}).fill('old-password-long');await page.getByRole('textbox',{name:'새 비밀번호',exact:true}).fill('new-password-long');await page.getByRole('button',{name:'비밀번호 저장',exact:true}).click();await expect(page.getByRole('button',{name:'로그인',exact:true})).toBeVisible();
});
